### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by antoineL**
Hi Shawn, seems you are back looking to improve your very useful package (thanks for it BTW.)

### CODE REVIEW

**Comment by ShawnMilo** [comment]
Thanks for the help, and attention to detail!

**Comment by antoineL** [comment]
I hate that, but it happens :-(
A point in the documentation I wrote earlier is wrong.
Can you please also commit 9f50dc944b1d5001e5e59f2f1cfc251a0f4b8572

**Comment by ShawnMilo** [comment]
I don't see an easy way to apply that commit, but if you make a PR I'll merge it.

**Comment by antoineL** [comment]
Done, it is now #15

**Pull request merged**
